force-app/main/default/objects/WeatherBit__mdt/WeatherBit__mdt.object-meta.xml
<CustomObject>
    <description>WeatherBit API configurations</description>
    <label>WeatherBit</label>
    <pluralLabel>WeatherBits</pluralLabel>
</CustomObject>

force-app/main/default/objects/WeatherBit__mdt/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <description>WeatherBit API Key</description>
    <inlineHelpText>WeatherBit API Key</inlineHelpText>
    <label>API Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WeatherBit__mdt/fields/Base_URL__c.field-meta.xml
<CustomField>
    <fullName>Base_URL__c</fullName>
    <description>WeatherBit API base URL</description>
    <inlineHelpText>WeatherBit API base URL</inlineHelpText>
    <label>Base URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WeatherBit__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>WeatherBit endpoint URL</description>
    <inlineHelpText>WeatherBit endpoint URL</inlineHelpText>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WeatherController.cls
/*
 * Apex wrapper for the WeatherBit REST API.
 * API documentation is available here: https://www.weatherbit.io/api/weather-forecast-16-day
 */
public with sharing class WeatherController {

    private static sObject weatherBitConfig;
    private final static String METHOD = 'GET';
    
    static {
        weatherBitConfig = Utility.getMetadata('WeatherBit__mdt').get('Daily Forcasts');
    }
    
    /*****************************************************************************************************************************
     * Method Name : getWeatherForcast
     * Parameters : q - API query parameter.
     * Return type : String - Response JSON string.
     */
    @AuraEnabled(continuation=true cacheable=true)
    public static String getWeatherForcast(String q) {
        String url = 
            String.valueOf(weatherBitConfig.get('Base_URL__c')) + 
            String.valueOf(weatherBitConfig.get('Endpoint__c')) +
            '?' + q + 
            '&key=' + String.valueOf(weatherBitConfig.get('API_Key__c'));
        
        HttpRequest req = new HttpRequest();
        Http http = new Http();        
        req.setMethod(METHOD);    
        req.setEndpoint(url);
		try {
            HTTPResponse res = http.send(req);
			return res.getBody();        	
        } catch(Exception ex){
            return '{"error": "' + ex.getMessage() + '"}';
        }        
    }
}